
# header code
p = 0
array = [0]*30_000
# begin trans-pile


array[p]=ord(input('? '))
print(chr(array[p]), end='')
array[p]=ord(input('? '))
print(chr(array[p]) * 2, end='')
array[p]=ord(input('? '))
array[p] += 11
p += 1
array[p] += 1
p += 4
array[p] += 44
p += 1
array[p] += 32
p -= 6
while array[p] != 0:
    p += 1
    while array[p] != 0:
        p += 6
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 7
        array[p] -= 1
    p += 7
    while array[p] != 0:
        p -= 7
        array[p] += 1
        p += 7
        array[p] -= 1
    p -= 1
    while array[p] != 0:
        p += 1
        array[p] += 10
        while array[p] != 0:
            array[p] -= 1
            p -= 1
            array[p] -= 1
            while array[p] != 0:
                p += 2
                array[p] += 1
                p += 1
                array[p] += 1
                p -= 3
                array[p] -= 1
            p += 3
            while array[p] != 0:
                p -= 3
                array[p] += 1
                p += 3
                array[p] -= 1
            array[p] += 1
            p -= 1
            while array[p] != 0:
                p += 1
                while array[p] != 0:
                    array[p] -= 1
                p -= 1
                while array[p] != 0:
                    array[p] -= 1
            p += 1
            while array[p] != 0:
                p -= 2
                while array[p] != 0:
                    p += 3
                    array[p] += 1
                    p -= 3
                    array[p] -= 1
                p += 2
                while array[p] != 0:
                    array[p] -= 1
            p -= 2
        p += 3
        while array[p] != 0:
            p += 2
            array[p] += 1
            p += 1
            array[p] += 1
            p -= 3
            array[p] -= 1
        p += 3
        while array[p] != 0:
            p -= 3
            array[p] += 1
            p += 3
            array[p] -= 1
        array[p] += 1
        p -= 1
        while array[p] != 0:
            p += 1
            while array[p] != 0:
                array[p] -= 1
            p -= 1
            while array[p] != 0:
                array[p] -= 1
        p += 1
        while array[p] != 0:
            p -= 2
            array[p] += 1
            p += 2
            while array[p] != 0:
                array[p] -= 1
        p -= 7
    p += 5
    while array[p] != 0:
        array[p] += 48
        print(chr(array[p]), end='')
        while array[p] != 0:
            array[p] -= 1
    array[p] += 10
    p -= 1
    while array[p] != 0:
        array[p] -= 1
        p += 1
        array[p] -= 1
        p -= 1
    p += 1
    array[p] += 48
    print(chr(array[p]), end='')
    while array[p] != 0:
        array[p] -= 1
    p -= 12
    while array[p] != 0:
        p += 3
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 4
        array[p] -= 1
    p += 4
    while array[p] != 0:
        p -= 4
        array[p] += 1
        p += 4
        array[p] -= 1
    p -= 1
    array[p] -= 1
    while array[p] != 0:
        p += 2
        print(chr(array[p]), end='')
        p += 1
        print(chr(array[p]), end='')
        p -= 3
        while array[p] != 0:
            array[p] -= 1
    p -= 2
    while array[p] != 0:
        p += 2
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 3
        array[p] -= 1
    p += 3
    while array[p] != 0:
        p -= 3
        array[p] += 1
        p += 3
        array[p] -= 1
    p -= 2
    while array[p] != 0:
        p -= 1
        array[p] += 1
        p += 1
        array[p] -= 1
    p += 1
    while array[p] != 0:
        p -= 1
        array[p] += 1
        p += 1
        array[p] -= 1
    p -= 3
    array[p] -= 1
array[p] += 11
p += 1
array[p] += 1
p += 4
array[p] += 44
p += 1
array[p] += 32
p -= 6
while array[p] != 0:
    p += 1
    while array[p] != 0:
        p += 6
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 7
        array[p] -= 1
    p += 7
    while array[p] != 0:
        p -= 7
        array[p] += 1
        p += 7
        array[p] -= 1
    p -= 1
    while array[p] != 0:
        p += 1
        array[p] += 10
        while array[p] != 0:
            array[p] -= 1
            p -= 1
            array[p] -= 1
            while array[p] != 0:
                p += 2
                array[p] += 1
                p += 1
                array[p] += 1
                p -= 3
                array[p] -= 1
            p += 3
            while array[p] != 0:
                p -= 3
                array[p] += 1
                p += 3
                array[p] -= 1
            array[p] += 1
            p -= 1
            while array[p] != 0:
                p += 1
                while array[p] != 0:
                    array[p] -= 1
                p -= 1
                while array[p] != 0:
                    array[p] -= 1
            p += 1
            while array[p] != 0:
                p -= 2
                while array[p] != 0:
                    p += 3
                    array[p] += 1
                    p -= 3
                    array[p] -= 1
                p += 2
                while array[p] != 0:
                    array[p] -= 1
            p -= 2
        p += 3
        while array[p] != 0:
            p += 2
            array[p] += 1
            p += 1
            array[p] += 1
            p -= 3
            array[p] -= 1
        p += 3
        while array[p] != 0:
            p -= 3
            array[p] += 1
            p += 3
            array[p] -= 1
        array[p] += 1
        p -= 1
        while array[p] != 0:
            p += 1
            while array[p] != 0:
                array[p] -= 1
            p -= 1
            while array[p] != 0:
                array[p] -= 1
        p += 1
        while array[p] != 0:
            p -= 2
            array[p] += 1
            p += 2
            while array[p] != 0:
                array[p] -= 1
        p -= 7
    p += 5
    while array[p] != 0:
        array[p] += 48
        print(chr(array[p]), end='')
        while array[p] != 0:
            array[p] -= 1
    array[p] += 10
    p -= 1
    while array[p] != 0:
        array[p] -= 1
        p += 1
        array[p] -= 1
        p -= 1
    p += 1
    array[p] += 48
    print(chr(array[p]), end='')
    while array[p] != 0:
        array[p] -= 1
    p -= 12
    while array[p] != 0:
        p += 3
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 4
        array[p] -= 1
    p += 4
    while array[p] != 0:
        p -= 4
        array[p] += 1
        p += 4
        array[p] -= 1
    p -= 1
    array[p] -= 1
    while array[p] != 0:
        p += 2
        print(chr(array[p]), end='')
        p += 1
        print(chr(array[p]), end='')
        p -= 3
        while array[p] != 0:
            array[p] -= 1
    p -= 2
    while array[p] != 0:
        p += 2
        array[p] += 1
        p += 1
        array[p] += 1
        p -= 3
        array[p] -= 1
    p += 3
    while array[p] != 0:
        p -= 3
        array[p] += 1
        p += 3
        array[p] -= 1
    p -= 2
    while array[p] != 0:
        p -= 1
        array[p] += 1
        p += 1
        array[p] -= 1
    p += 1
    while array[p] != 0:
        p -= 1
        array[p] += 1
        p += 1
        array[p] -= 1
    p -= 3
